AllCops:
  TargetRubyVersion: 2.7.0
  Exclude:
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'spec/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'app/channels/**/*'
    - 'app/jobs/**/*'
    - 'app/mailers/**/*'
    - 'Rakefile'
    - 'Config.ru'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/EndOfLine:
  Exclude:
    - 'app/models/**/*'
    - 'app/controllers/application_controller.rb'

Layout/LineLength:
  Exclude:
    - 'app/concepts/seances/use_cases/available_seats.rb'
